feat: update ci-cd setting

diff --git a/.github/workflows/docker-hub-ci-cd.yml b/.github/workflows/docker-hub-ci-cd.yml
--- a/.github/workflows/docker-hub-ci-cd.yml
+++ b/.github/workflows/docker-hub-ci-cd.yml
@@ -3,24 +3,62 @@ name: CI/CD
 on: [push] # 执行时机
 # 任务
 jobs:
+  # Build job
   build:
-    # 运行的环境
     runs-on: ubuntu-latest
-    # 步骤
     steps:
-      - uses: actions/checkout@v2 # git pull
-      - name: Use Node.js
-        uses: actions/setup-node@v1
-        with:
-          node-version: 16
-      - name: 打包镜像, 上传 Docker Hub
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
         run: |
-          echo "secrets:" ${{ secrets.DOCKER_USERNAME }}
-          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
-          docker build -t bpmn-camunda-image  .
-          docker tag bpmn-camunda-image ${{ secrets.DOCKER_REPOSITORY }}
-          docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Setup Pages
+        uses: actions/configure-pages@v2
+        with:
+          # Automatically inject router.base in your Nuxt configuration file and set
+          # target to static (https://nuxtjs.org/docs/configuration-glossary/configuration-target/).
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: nuxt
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            dist
+            .nuxt
+          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
+          restore-keys: |
+            ${{ runner.os }}-nuxt-build-
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Static HTML export with Nuxt
+        run: ${{ steps.detect-package-manager.outputs.manager }} run generate
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ./dist
 
+  # Deployment job
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
       - name: 登录服务器, 执行脚本
         uses: appleboy/ssh-action@master
         with:
